### ISSUE TITLE
How to get refresh token?

### ISSUE THREAD

**Issue by sarat12us** [appsup-dart/openid_client#24]
Is there anyway I can get refresh token, I am using web client and AuthorizationPKCE grant type. 
I don't see any interface to get refresh token. Any help?

**Comment by danielleiszen** [comment]
We have this problem as well. Any suggested method or solution on refreshing the token using this client? Or is this repo not maintained or a different client library is suggested? Because in that case it should be noted and we will switch to another implementation. If contribution is needed we would be happy to help. Please let us know, thanks.

**Comment by rbellens** [comment]
You can get the refresh token as:

```dart
var token = await credential.getTokenResponse();
print(token.refreshToken);
```
