### ISSUE TITLE
Redirection to Keycloak not working using openid package for flutter app

### ISSUE THREAD

**Issue by talbiislam96** [appsup-dart/openid_client#32]
Currently building a flutter app that uses keycloak to authenticate users. The user is supposed to click on the login button that will take him to the web interface built using keycloak , after the authentication the user will be brought back to the app (home page ) after getting the token. Since I have no idea how this is supposed to work I followed this example [Example Link][1]

This is my function : 
```
 authenticate() async {
    var uri = Uri.parse('http://10.0.2.2:8080/auth/realms/clients');
    var clientId = 'helium';
    var scopes = List<String>.of(['openid', 'profile']);
    var port = 4200;
    var redirectUri = Uri.parse('http://localhost:4200');

    var issuer = await Issuer.discover(uri);
    var client = new Client(issuer, clientId);

    urlLauncher(String url) async {
      if (await canLaunch(url)) {
        await launch(url, forceWebView: true);
      } else {
        throw 'Could not launch $url';
      }
    }

    var authenticator = new Authenticator(client,
      scopes: scopes,
      port: port,
      urlLancher: urlLauncher,);

    var c = await authenticator.authorize();
    closeWebView();

    var token= await c.getTokenResponse();
    print(token);
    return token;
  }




```
Am calling it inside a button: 

``` 

   RoundedButton(
              text: "Login",
                press: (){


                authenticate();
                }

                //Navigator.push(
                  //context,
                 //MaterialPageRoute(
                  // builder: (context) {
                     //return MainMenu();
                    //},
                 // ),
               //);


                 ,
            ),







 ```
this is the stack trace : 

``` 

E/flutter ( 5769): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Instance of 'HttpRequestException'
E/flutter ( 5769): #0      _processResponse (package:openid_client/src/http_util.dart:37:5)
E/flutter ( 5769): #1      get (package:openid_client/src/http_util.dart:18:10)
E/flutter ( 5769): <asynchronous suspension>
E/flutter ( 5769): #2      Issuer.discover (package:openid_client/src/openid.dart:124:16)
E/flutter ( 5769): <asynchronous suspension>
E/flutter ( 5769): #3      Body.authenticate (package:helium_app/screens/login/components/body.dart:35:18)
E/flutter ( 5769): <asynchronous suspension>




```
Am I missing something ? if anyone knows how to make this work , plz don't hesitate to help and guide me through this , also I would love to know how to generate a link to my home page to redirect the user to it instead of the redirection URI am using in the function 'http://localhost:4200' 

thank u in advance

  [1]: https://github.com/appsup-dart/openid_client/issues/11#issuecomment-603232319

**Comment by funder7** [comment]
You're using a wrong redirection url. 
Basically you need to define a "special" url scheme, which will redirect the login view back to your app, once the autentication process is completed. 

how? Your application has a base name like com.mycompany.myappname.
The final scheme definition will be:  com.mycompany.myappname://whatever

Once you have a an application with that base name installed, the OS on the phone, independently if it's Android or iOS will try to open the link from that application.

What must be done is to tell keycloak that once the login process is completed, it must redirect the user to the app. 
You do that by setting keycloak, it must be configured in order to recognize the app scheme.

The settings is relative to the client you will connect to (helium in your case), so if you open the helium client settings, there will be a box where the url scheme can be configured:

![immagine](https://user-images.githubusercontent.com/12503478/105356772-1e187800-5bf4-11eb-8bd1-5d8c4afb6430.png)

If you don't see it, probably the client must be configured properly (Standard flow must be enabled, or you will not see it).

Next step, the application must be configured to recognize the url scheme. This is plugin-related, so check the documentation to see how to do it please. 

Finally, when calling the Auth server from your app, 
`var redirectUri = Uri.parse('http://localhost:4200');`

This url must be replaced with: `com.mycompany.myappname://<whatever>`

If you follow these steps, login and redirection will work!

**Comment by funder7** [comment]
Hi @talbiislam96, thank you for the feedback!

**Comment by drsarutobi8** [comment]
@funder7 
> Next step, the application must be configured to recognize the url scheme. This is plugin-related, so check the documentation to see how to do it please.

Could you please explain regarding to this? Do you mean it relates to openId_client plugin? Sadly, I cannot find any.
Here is what I have:
android/app/build.gradle
```
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.studentsinformation.frontend"
        minSdkVersion 18
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.studentsinformation.frontend'
        ]
    }
```
 My keycloak setting for Valid Redirect URIs is
com.studentsinformation.frontend://*

main.dart
```
...
    try {
      final Issuer issuer = await Issuer.discover(Uri.parse(AUTH_ISSUER));
      final Client client =
          Client(issuer, AUTH_CLIENT_ID, clientSecret: AUTH_CLIENT_SECRET);
      debugPrint(issuer.metadata.toString());
      urlLauncher(String url) async {
        if (await canLaunch(url)) {
          await launch(url, forceWebView: true);
        } else {
          throw 'Could not launch $url';
        }
      }

      Authenticator authenticator = Authenticator(
        client,
        scopes: AUTH_SCOPES,
        // port: REDIRECT_PORT,
        urlLancher: urlLauncher,
        redirectUri: Uri.parse(REDIRECT_URI),
      );
      _credential = await authenticator.authorize();
      closeWebView();
      final TokenResponse token = await _credential.getTokenResponse();
      final UserInfo userInformation = await _credential.getUserInfo();

      await secureStorage.write(
          key: 'refresh_token', value: token.refreshToken);
...
```
the app shows keycloak login and I can login successfully. But it  shows web page as:
```
Webpage not available

The webpage at
http://com.studentsinformation.frontend//login-callback?state=15Qx....

because:

net:: ERR_CLEARTEXT_NOT_PERMITTED
```
Please help.

**Comment by funder7** [comment]
Please give me a little more background (or screenshot) of the various steps
I'm not understanding what do you mean with "Web page".


The error that you are facing is very likely related to http/https
protocol.

Basically you are trying to open an http url, but latest android/ios
versions don't support it out of the box.

In android, you can search how to enable http navigation through xml config
(enable it only in dev mode, not production app).

In ios is not that easy. I lost some time to make it work.

There are different roads that you can follow, I don't know which one is
the easier.

In my setup, I had the backend and keycloak behind a local reverse proxy:

- /api/* was redirected to backend on localhost:8080

- /auth/* was redirected to keycloak, on localhost:9080

Now I was able to access both servers on a single port (http 80)

I created a ngrok service to expose this address on a public domain,
through https.

The tricky part is that every time you start ngrok, it generates a new
domain name, which you need to copy into every service using keycloak,
otherwise tokens will be invalid due to wrong issuer.

In my case I've created a script to start ngrok and update every
configuration file accordingly.

Now some time has passed and I'm not working anymore on this project, but I
can share the script if you need it.

Honestly, I suggest you to verify if it's possible to enable http clear
text in android xml, and use keycloak through http in local development, to
avoid all this hassle.

Once you will gain confidence with keycloak and how oauth works, you can
think to configure the ios simulator and work behind https.

Good luck


Il ven 22 ott 2021, 01:14 Apichat Banyatsupasil ***@***.***>
ha scritto:
