### ISSUE TITLE
Can we use custom scheme instead of embedded server, with this library. Can you please guide me, how to achieve it

### ISSUE THREAD

**Issue by sanketbajoria** [appsup-dart/openid_client#45]

**Comment by rbellens** [comment]
The `Authenticator` class in `openid_client_io.dart` uses a server to capture the response from an auth request. If you need to handle it otherwise, e.g. with a redirect uri that deep links into the app, you can implement your own `Authenticator` like class, possibly using packages like `uni_links`. You would need to launch the `flow.authenticationUri` in a browser and somehow capture the response and then call the `flow.callback` to exchange this for a token.
