### ISSUE TITLE
Using openID for keycloak error

### ISSUE THREAD

**Issue by dylan-dinh** [appsup-dart/openid_client#9]
Hello,

I have been trying through de command line to add clients like that : 
`openid_client clients configure https://my_realm_keycloak client_id`

error throw : 
`type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'`

I tried this as well : 
`openid_client clients configure --secret my_scret_keycloak https://my_realm_keycloak client_id`

same error throw : 
`type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'`

Do you have any ideas ? thanks in advance :)

**Comment by markusschuh** [comment]
Seems to be caused by ["return {}"](https://github.com/appsup-dart/openid_client/blob/873ce0f4589e170c70b9e5a6dc3d0b656ec4fd24/bin/openid_client.dart#L289) which is triggered, when a _configFile does not yet exists.

Workaround; Create a configfile with empty json - {} - at `$HOME/.openid_client/config.json`or `%APPDATA%\OpenIdClient\config.json`

proposed code fix: 
`return json.decode('{}');`
instead of the
`return {};`
